{{ if (eq .Values.werf.env "dev") }}
{{- $replicaCount := index .Values "replicaCount" -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-dev
  labels:
    app: {{ .Chart.Name }}-dev
spec:
  serviceName: {{ .Chart.Name }}-dev
  replicas: {{ $replicaCount }}
  selector:
      matchLabels:
        app: {{ .Chart.Name }}-dev
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-dev
    spec:
      initContainers:
      - name: prepare-dev-env
        image: '{{ index .Values.werf.image (printf "%s-dev" .Chart.Name) }}'
        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}-common-config
        command: [ "/bin/bash", '-c' ]
        args:
          -
            source /install/prepare-scripts/init-dev-env.sh;
        volumeMounts:
        - mountPath: /workspace
          name: workspace
        - name: id-rsa-vcs
          mountPath: "/root/.ssh/id_rsa"
          subPath: "id_rsa" 
      containers:
      - name: {{ .Chart.Name }}-dev
        image: '{{ index .Values.werf.image (printf "%s-dev" .Chart.Name) }}'
        env:
        - name: PROJECT
          value: {{ printf "%s-%s" .Chart.Name .Values.werf.env}}
        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}-common-config

        volumeMounts:
          - mountPath: /workspace
            name: workspace
          - name: id-rsa-vcs
            mountPath: "/root/.ssh/id_rsa"
            subPath: "id_rsa"  
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName:  {{ .Chart.Name }}-workspace-pv-claim
        - name: id-rsa-vcs
          secret:
            secretName: id-rsa-vcs
            defaultMode: 0600
---
{{ end }}